name: "Vault GHA"

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    name: retrieve-secret
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault-sgp-cluster-public-vault-cd02ce11.efe1a776.z1.hashicorp.cloud:8200
          namespace: admin
          method: jwt
          path: jwt-github-actions
          role: app1
          exportToken: true
          secrets: |
            kv/data/app1 password | PASSWORD ;
        env: 
          PASSWORD: ${{ secrets.password }}
      - name: Print secrets
        run: |
          echo "${{ env.PASSWORD }}"
      - name: Revoke Vault Token
        if: always()
        run: |
          curl -X POST -sv --fail-with-body -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" \
            https://vault-sgp-cluster-public-vault-cd02ce11.efe1a776.z1.hashicorp.cloud:8200/v1/auth/token/revoke-self