name: "Vault GHA"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  retrieve-secret:
  runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault-sgp-cluster-public-vault-cd02ce11.efe1a776.z1.hashicorp.cloud:8200
          role: app1
          method: jwt
          jwtGithubAudience: sigstore
          namespace: admin
          secrets: |
            kv/data/aws AWS_ACCESS_KEY_ID | AWS_ACCESS_KEY_ID ;
            kv/data/aws AWS_SECRET_ACCESS_KEY | AWS_SECRET_ACCESS_KEY
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Print secrets
        run: |
          echo "${{ env.AWS_ACCESS_KEY_ID }}"
          echo "${{ steps.import-secrets.outputs.AWS_SECRET_ACCESS_KEY }}"